# good idea to move that image under organization name
image: pavelkhritonenko/aws-kubectl

services:
  - docker:dind

build-and-push:
  only:
    - tags
    - master
    - /^feature\/(.*)$/
    - /^bugfix\/(.*)$/

  script:
    - docker run --rm mikesir87/aws-cli:latest aws ecr get-login --region us-west-2 --no-include-email | sh
    - DOCKER_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's;/;-;g')
    - DOCKER_REGISTRY=$AWS_DOCKER_REGISTRY_URL/$CI_PROJECT_NAME
    - DOCKER_REF=$DOCKER_REGISTRY:$DOCKER_TAG
    - docker build -t $DOCKER_REF
      --build-arg VERSION=${CI_COMMIT_REF_NAME}
      --build-arg PROJECT_NAME=${CI_PROJECT_NAME}
      --build-arg COMMIT=${CI_COMMIT_SHA}
      --build-arg NPMRC="${NPMRC}"
      --build-arg SSH_KEY="${SSH_BUILD_BOT_KEY}"
      -f deployment/Dockerfile .
    - docker push $DOCKER_REF
    - >
      if [[ $DOCKER_TAG =~ (([0-9]+)\.[0-9]+)\.[0-9]+ ]]; then
        MAJOR_TAG=${BASH_REMATCH[2]}
        MINOR_TAG=${BASH_REMATCH[1]}
        docker tag $DOCKER_REF $DOCKER_REGISTRY:$MINOR_TAG
        docker tag $DOCKER_REF $DOCKER_REGISTRY:$MAJOR_TAG
        docker push $DOCKER_REGISTRY:$MINOR_TAG
        docker push $DOCKER_REGISTRY:$MAJOR_TAG
      fi
